# Generated by Django 3.2.3 on 2021-08-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='id',
            new_name='category_id',
        ),
    ]
