# Generated by Django 3.2.3 on 2021-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210825_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='amount',
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
