# Generated by Django 3.2.3 on 2021-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210825_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
